name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    name: Int√©gration serveur PROD
    runs-on: ubuntu-latest
    steps:
    - name: Update de l'API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker exec projet_node pm2 stop /home/projet/app.js
          cd /home/git/projetIntegrationGrp6
          sudo git pull
          sudo cp /home/git/projetIntegrationGrp6/Node.js/* /home/projet/node/ -r
          sudo docker exec projet_node npm install
          sudo docker exec projet_node pm2 start /home/projet/app.js -f
          
          
